import Head from 'next/head';
import Hero from '../components/Hero';
import Instagram from '../components/Instagram';
import Slider from '../components/Slider';
import { sliderData } from '../components/sliderData';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Hero
        heading="Cature Photography"
        message="I capture moments in nature and keep them alive."
      />
      <Slider slides={sliderData} />
      <Instagram />
    </div>
  );
}
